# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e407efbbac59c56adc3fa45557ed9e7f5ad46a195e209553cf5e6f730f7350ef7abc435ca4b900f1e0567e0dbc3a13e2c09410f13269d14f87e9a969a224b10

test:
  secret_key_base: 75219f326584ca1ed37575e6fd00441132aa0e3a449fa8568b9f7f1c52030ab5ecc30e45eea48e069af564d6a44f0831e5f2cfc6dd74a2d84ab022420bb342ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
